### ISSUE TITLE
Cannot export to pdf

### ISSUE THREAD

**Issue by clyang82** [melix/deck2pdf#18]
I have tried to use deck2pdf to export HTML 5 ppt (flowtime.js) to pdf. unfortunately, not all pages can be exported successfully. some of pages are gray without any content. do you have the same experience? Thanks.

**Comment by qanx** [comment]
I have this experience all the time - usually if the slide deck is more than a given number of slides. (On a Macbook Air w/ 8 GB of RAM I had a 40 slide limit before this would happen, on a Macbook Pro w/ 16 GB of RAM it will only do 8. Both laptops are < 2 years old and running the latest release of OS 10.10.)

It's notably not awesome, but until I have time re-write my own version of this tool it's something to live with.

**Comment by melix** [comment]
Maybe it's just a memory issue. Can you try running with:

```
JAVA_OPTS=-Xmx2G deck2pdf slides.pdf
```

**Comment by qanx** [comment]
Just gave it a couple of tries. On a regular deck (most of our decks hover around 20 slides), so I tried with one of those. The JavaFX window froze on the first slide (for > 10 minutes, I just let it "run" and walked away). When I killed it, I received the following error:

```
netscape.javascript.JSException: ReferenceError: Can't find variable: $
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1426)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:948)
	at me.champeau.deck2pdf.JSProfile.getSlideCount(JSProfile.java:73)
	at me.champeau.deck2pdf.Browser$1.handle(Browser.java:126)
	at me.champeau.deck2pdf.Browser$1.handle(Browser.java:111)
	at javafx.animation.Animation.impl_finished(Animation.java:1132)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at javafx.animation.Animation$1$$Lambda$159/1765243050.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:431)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$363(QuantumToolkit.java:298)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$42/1014046706.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

It's worth mentioning that when I partition the deck into separate HTML presentations of 7 slides or less each that it works "normally" (without the variable). As an aside, I also had Activity Monitory open and overall I have about 8 GB or more free and minimal swap usage (on the order of 10s of MB).

**Comment by melix** [comment]
Right. Might be that the app started to export slides before it could load the external dependencies (like JS libraries). I am unsure because I don't face this problem but the error you pasted seems to indicate that a required object ($) is missing, which can be caused by a missing JS library.

**Comment by qanx** [comment]
If there was a missing JS library, wouldn't that be true for both the "unaltered" deck and the "minidecks" (i.e. when I break the deck down into groups of 7 slides)?

**Comment by melix** [comment]
I think that when you split the deck, deck2pdf has more time to load the page (because it is shorter), so it has more chances to grab the dependencies. I am just speculating though.

**Comment by qanx** [comment]
Do you have any other thoughts of things that I can try to resolve this? I'm not a Java developer (and I'm new to software generally speaking) and thus far I've been hitting a wall.

**Comment by melix** [comment]
I am not sure it will work, but try this: in this impress.js profile https://github.com/melix/deck2pdf/blob/master/src/main/resources/impressjs.groovy#L21 you can see that I override the time required before starting the export. It is not done for flowtime. You can alter https://github.com/melix/deck2pdf/blob/master/src/main/resources/flowtimejs.groovy by adding a similar pause, then build the application again and see if it works.

Let me know.

**Comment by qanx** [comment]
Unfortunately adding `pause = 2000` resulted in the same problem: freezing at the first slide and throwing the above error msg.

**Comment by melix** [comment]
Even with bigger number? 10000 would be 10s before starting export for example. If not, then I fear I am running out of ideas :/

**Comment by qanx** [comment]
Tried 10000, no change :( I also increased the pause [in impressjs.groovy](https://github.com/melix/deck2pdf/blob/master/src/main/resources/impressjs.groovy#L21) to 10000 to see if that mattered, but both resulted in the same behavior. :(

**Comment by qanx** [comment]
I am using the latest version of Java to compile, what version of Java do you use? What is your system information? (I ask because you said that you never encountered this issue but I've seen it on at least two Macs now)
![screen shot 2015-01-22 at 10 07 24 am](https://cloud.githubusercontent.com/assets/3387286/5858102/a1abdf22-a21e-11e4-8d1d-fd3db5118a3c.png)

**Comment by melix** [comment]
I am not on Mac OS but I tested with various JDK 8 versions (up to 8u60).

**Comment by qanx** [comment]
What version/flavor/etc. of Linux are you using? I have some spare hardware that I can use to test this puppy out. (I really want to figure this out, heh.)

**Comment by melix** [comment]
Linux Mint 17 (64bit)

**Comment by qanx** [comment]
ok, thank you! I'll let you know if/when I figure out what's going on.

**Comment by qanx** [comment]
Update: the other day it was "working" in the sense that I could get the slides build if the HTML deck was 7 slides or less. Today, despite rebooting, reinstalling the Java JDK, and rebuilding `deck2pdf` the app immediately crashes. Have you seen this before?

```
Exception in Application start method
Java has been detached already, but someone is still trying to use it at -[GlassRunnable run]:/HUDSON/workspace/8u31/label/macosx-universal-30/rt/modules/graphics/src/main/native-glass/mac/GlassApplication.m:92
Java has been detached already, but someone is still trying to use it at -[GlassRunnable dealloc]:/HUDSON/workspace/8u31/label/macosx-universal-30/rt/modules/graphics/src/main/native-glass/mac/GlassApplication.m:106
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:363)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
	at com.sun.javafx.application.LauncherImpl$$Lambda$49/1099983479.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Cannot find a profile named 'impressj
	at me.champeau.deck2pdf.ProfileLoader.loadProfile(ProfileLoader.java:59)
	at me.champeau.deck2pdf.Main.start(Main.java:84)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
	at com.sun.javafx.application.LauncherImpl$$Lambda$52/2123770744.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/128893786.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/899036353.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/1108411398.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application me.champeau.deck2pdf.Main
```

**Comment by melix** [comment]
Did you forget an `s` to the profile name? The message says:

`Cannot find a profile named 'impressj`

**Comment by qanx** [comment]
Ack I didn't even notice I had done that. Thank you! Sorry >.<
